spring.application.name=campusfit-backend

spring.datasource.url=jdbc:mysql://localhost:3306/campusfit
spring.datasource.username=root
spring.datasource.password=Varun@364

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=8080

